### PR TITLE
Commit activity badge fixed

### PR DESCRIPTION
**Pull request by WhiteBlackGoose**
You might've forgotten to change `badges/shields` to your repository for commit activity badge :). I also changed from month to year so that it wasn't 0.

### CODE REVIEW

**Comment by AraHaan** [comment]
Oh thanks, btw mind amending the ``--signoff`` on git, and force pushing that amending?

**Comment by WhiteBlackGoose** [comment]
Meh, should've used just `--force`. Anyway, are you going to squash it?

**Comment by WhiteBlackGoose** [comment]
@AraHaan check now

**Comment by AraHaan** [comment]
Thanks, not sure if this applies to this repository or not (since I use codacy on this repository) https://about.codecov.io/security-update/.

btw: You should check if you was affected by it as well too on your CI's, now I got to go through and check which repositories of mine was affected sadly.

Also you mind checking the other non archived repositories for this same badge issue as well? @WhiteBlackGoose

**Comment by WhiteBlackGoose** [comment]
> btw: You should check if you was affected by it as well too on your CI's, now I got to go through and check which repositories of mine was affected sadly.

My repo was affected, I was emailed. At that moment the page you shared yielded 500 error XD, but now it works. Thanks for reminding!

**Comment by WhiteBlackGoose** [comment]
> Also you mind checking the other non archived repositories for this same badge issue as well? @WhiteBlackGoose

Sure I can check

**Review by AraHaan — APPROVED** [review]

**Comment by AraHaan** [comment]
oof it does not want to automerge with the label...

**Comment by AraHaan** [comment]
Ah I see I do not use the default ``GITHUB_TOKEN`` and I set it to an ``PAT`` which is only set for prs from this repository from a feature branch and not from forks. 🤦

Oh ye that reminds me I forgot to add commit activity badge to Els_kom_new, and zlib.managed.

**Pull request merged**
